version: '3.8'
services:

  my-website:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - node_modules:/app/node_modules
      - .:/app
    ports:
      - "5173:5173"
    networks:
      - my-website-net

  dragonfly:
    image: 'docker.dragonflydb.io/dragonflydb/dragonfly'
    ulimits:
      memlock: -1
    ports:
      - "6379:6379"
    volumes:
      - dragonflydata:/data
    networks:
      - my-website-net

volumes:
  node_modules:
  dragonflydata:

networks:
  my-website-net:
