name = "peter-website"
pages_build_output_dir = "./dist"
compatibility_date = "2024-05-16"
compatibility_flags = ['nodejs_compat']

[vars]
UNSTABLE_PRE_BUILD = "bun upgrade"

[placement]
mode = "smart"
